name: sma_combined_analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.18
  - aiosignal=1.3.2
  - aom=3.9.1
  - appnope=0.1.4
  - asciitree=0.3.3
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - aws-c-auth=0.9.0
  - aws-c-cal=0.8.9
  - aws-c-common=0.12.2
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.5
  - aws-c-io=0.18.0
  - aws-c-mqtt=0.12.3
  - aws-c-s3=0.7.15
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.5
  - aws-crt-cpp=0.32.4
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blosc=1.21.6
  - bokeh=3.7.2
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.15.2
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.2
  - cpython=3.10.17
  - cycler=0.12.1
  - cytoolz=1.0.1
  - dask=2024.11.2
  - dask-core=2024.11.2
  - dask-expr=1.1.19
  - dask-image=2024.5.3
  - datashader=0.18.0
  - dav1d=1.2.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - distributed=2024.11.2
  - docrep=0.3.2
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fasteners=0.19
  - filelock=3.18.0
  - folium=0.19.5
  - freetype=2.13.3
  - freexl=2.0.0
  - frozenlist=1.5.0
  - fsspec=2025.3.2
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.13.1
  - geotiff=1.7.4
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h2=4.2.0
  - h5py=3.13.0
  - hdf5=1.14.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagecodecs=2024.12.30
  - importlib-metadata=8.6.1
  - inflect=7.5.0
  - ipykernel=6.29.5
  - ipython=8.35.0
  - jedi=0.19.2
  - joblib=1.4.2
  - json-c=0.18
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jxrlib=1.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libaec=1.1.3
  - libarchive=3.7.7
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libavif16=1.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.13.0
  - libcxx=20.1.3
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.4
  - libgdal-core=3.10.3
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libhwloc=2.11.2
  - libhwy=1.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libopentelemetry-cpp=1.20.0
  - libopentelemetry-cpp-headers=1.20.0
  - libparquet=19.0.1
  - libpng=1.6.47
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libutf8proc=2.10.0
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.7
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=20.1.3
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.8.1
  - markdown-it-py=3.0.0
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - matplotlib-scalebar=0.9.0
  - mdurl=0.1.2
  - minizip=4.0.9
  - more-itertools=10.7.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.4.3
  - multipledispatch=0.6.0
  - multiscale-spatial-image=2.0.2
  - munkres=1.1.4
  - narwhals=1.35.0
  - natsort=8.4.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - nomkl=1.0
  - numcodecs=0.13.1
  - ome-zarr=0.10.2
  - omnipath=1.0.8
  - openjpeg=2.5.3
  - openssl=3.5.0
  - optree=0.15.0
  - orc=2.1.1
  - pandas=2.2.3
  - param=2.2.0
  - parso=0.8.4
  - partd=1.4.2
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pims=0.7
  - pip=25.0
  - pooch=1.8.2
  - proj=9.6.0
  - prometheus-cpp=1.3.0
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pyct=0.5.0
  - pygments=2.19.1
  - pynndescent=0.5.13
  - pyogrio=0.10.0
  - pyproj=3.7.1
  - pysocks=1.7.1
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.6.0
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - rav1e=0.6.6
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - rich=14.0.0
  - scanpy=1.11.1
  - scikit-learn=1.5.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - session-info2=0.1.2
  - setuptools=75.8.0
  - shapely=2.1.0
  - sleef=3.8
  - slicerator=1.1.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - spatial-image=1.1.0
  - spatialdata=0.4.0
  - sqlite=3.49.1
  - squidpy=1.6.5
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=3.0.2
  - sympy=1.13.3
  - tbb=2022.1.0
  - tblib=3.1.0
  - tk=8.6.13
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typeguard=4.4.2
  - typing_extensions=4.13.2
  - umap-learn=0.5.7
  - unicodedata2=16.0.0
  - uriparser=0.9.8
  - validators=0.34.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.17.2
  - xarray=2024.11.0
  - xarray-dataclasses=1.9.1
  - xarray-schema=0.0.3
  - xarray-spatial=0.4.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.20.0
  - zarr=2.18.3
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zlib-ng=2.2.4
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - anndata==0.11.3
      - anyio==4.6.0
      - appdirs==1.4.4
      - array-api-compat==1.11
      - asgiref==3.8.1
      - attrs==25.1.0
      - beautifulsoup4==4.13.4
      - bioservices==1.12.1
      - cattrs==24.1.3
      - colorlog==6.9.0
      - configargparse==1.7
      - connection-pool==0.0.3
      - contourpy==1.3.0
      - datrie==0.8.2
      - docutils==0.21.2
      - dpath==2.2.0
      - easydev==0.13.3
      - fastjsonschema==2.21.1
      - fonttools==4.56.0
      - gevent==25.4.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.2.1
      - grequests==0.7.0
      - h11==0.14.0
      - html5lib==1.1
      - htmltools==0.5.3
      - humanfriendly==10.0
      - imageio==2.35.1
      - jinja2==3.1.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - legacy-api-wrap==1.4
      - line-profiler==4.2.0
      - linkify-it-py==2.0.3
      - llvmlite==0.43.0
      - lxml==5.4.0
      - markupsafe==3.0.1
      - matplotlib==3.9.2
      - mdit-py-plugins==0.4.2
      - nbformat==5.10.4
      - networkx==3.3
      - numba==0.60.0
      - numpy==1.26.4
      - packaging==24.1
      - pathlib==1.0.1
      - patsy==0.5.6
      - pillow==10.4.0
      - plac==1.4.3
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.36
      - pulp==2.5.1
      - pyparsing==3.1.4
      - pyreadline3==3.5.4
      - pyteomics==4.7.5
      - python-multipart==0.0.12
      - pytz==2024.2
      - questionary==2.0.1
      - referencing==0.36.2
      - requests-cache==1.2.1
      - reretry==0.11.8
      - rich-click==1.8.8
      - rpds-py==0.23.1
      - scikit-image==0.24.0
      - scipy==1.14.1
      - session-info==1.0.0
      - shiny==1.1.0
      - six==1.16.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - snakemake==7.32.4
      - sniffio==1.3.1
      - soupsieve==2.7
      - starlette==0.39.2
      - stdlib-list==0.11.1
      - stopit==1.1.2
      - suds-community==1.2.0
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - throttler==1.2.2
      - tifffile==2024.9.20
      - toposort==1.10
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uc-micro-py==1.0.3
      - url-normalize==2.2.0
      - urllib3==2.3.0
      - uvicorn==0.31.0
      - watchfiles==0.24.0
      - webencodings==0.5.1
      - websockets==13.1
      - xmltodict==0.14.2
      - yte==1.7.0
      - zope-event==5.0
      - zope-interface==7.2
